### ISSUE TITLE
[Feature] Use existing (or explicitly-named new?) data bucket

### ISSUE THREAD

**Issue by athewsey** [aws-solutions/improving-forecast-accuracy-with-machine-learning#11]
**Is your feature request related to a problem? Please describe.**

On a recent project implementing this solution, we wanted to be able to deploy the stack against an existing S3 data bucket... Or possibly set a particular name for the newly created data bucket. But doing so required customization of the CDK source.

**Describe the feature you'd like**

It would be great if the stack could expose an optional CFn parameter for users to set the name of a pre-existing data bucket to hook in to instead of creating new.

As a second (less important) possibility, would be nice if the stack supported optionally explicitly naming a data bucket to be newly created.

**Additional context**

N/A

**Comment by knihit** [comment]
Thank you for reaching out. We appreciate your feedback. The architecture is based on 's3:PutObject' which triggers the stepfunction workflow. Hence at this point it would not be possible to add this feature to our backlog. Closing this issue. Feel free to reach out for any other issues/ feature request that you are looking for in the solution.
