### ISSUE TITLE
RTS & Metadata error when used in 'Default' config

### ISSUE THREAD

**Issue by athewsey** [aws-solutions/improving-forecast-accuracy-with-machine-learning#12]
**Describe the bug**

When using the special `Default` configuration (for example, as we might if our deployment has only one config), setting up an RTS or Item Metadata dataset causes errors because the solution tries to start import for these datasets without/before creating the dataset.

**To Reproduce**

- Set up `forecast_defaults.yaml` with **only** a `Default` configuration, and in this default configuration specify RTS and Metadata datasets as well as TTS.
- Upload some set of `testadata.csv`, `testdata.related.csv`, `testdata.metadata.csv` to S3 (all at once)

The state machine will error, because the solution tries to import `testdata.related.csv` and `testdata.metadata.csv` before actually creating the datasets in the DSG.

**Expected behavior**

The solution should create all 3 datasets, import data, and train predictors: As it would if these same settings were made in an explicitly named configuration instead of using the `Default`.

**Please complete the following information about the solution:**
- [X] Version: v1.4.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "(SO0123) Improving Forecast Accuracy with Machine Learning v1.3.0[...]".

- [X] Region: `ap-southeast-1`
- [X] Was the solution modified from the version published on this repository? No
- [X] If the answer to the previous question was yes, are the changes available on GitHub?
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**

N/A

**Additional context**

This seems to be caused by the override in [Config.required_datasets()](https://github.com/aws-solutions/improving-forecast-accuracy-with-machine-learning/blob/efdc3a56a8f78b0d292f209d98e43e5cf60bd8fb/source/forecast-shared/shared/config.py#L359), which sets the list of "required" dataset types to [TTS] when the `Default` configuration is being used... Regardless of what is actually specified in the Default configuration.

**Comment by knihit** [comment]
Thank you for reaching out, we will try to reproduce the issue.
