### ISSUE TITLE
s3 bucket upload not triggering step functions and AttributeError: NoneType

### ISSUE THREAD

**Issue by nivedha75** [aws-solutions/improving-forecast-accuracy-with-machine-learning#13]
**Describe the bug**

Hi! I was able to create the stack without any errors, but when a modified version of the csv file is uploaded to the s3 bucket, the step functions are not automatically triggered and the aws forecast autopredictor is not trained. I get the following error when I manually click start execution in the step functions.

[ERROR] AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "/opt/python/shared/helpers.py", line 68, in wrapper
    (status, output) = f(event, context)
  File "/var/task/handler.py", line 29, in createdatasetgroup
    dataset_file = DatasetFile(event.get("dataset_file"), event.get("bucket"))
  File "/opt/python/shared/Dataset/dataset_file.py", line 36, in __init__
    if key.endswith(".related.csv")

It seems to say there is no related time series csv file, but that's optional according to the documentation. Thus, I included the related time series dataset csv file, but it still gives the error. I provided both target and related time series datasets in the Cloud Formation stack, but it still has the value 'None'.

I believe this error is occurring because there was no event that triggered the steps function (I click start execution button instead). AWS instructions regarding deploying AWS forecast models with AWS cloud formation stacks say that I should just upload a file to s3 and it will automatically trigger the step functions that deploy the AWS forecast model we created. When I upload a modified version of the csv file to s3, nothing happens and I am not given any error. Could you please help me figure out why the stack is not deploying automatically? Thx

**To Reproduce**
https://docs.aws.amazon.com/solutions/latest/improving-forecast-accuracy-with-machine-learning/automated-deployment.html
Using the improving-forecast-accuracy-with-machine-learning.template and the following yaml configuration file:

Default:
  DatasetGroup:
    Domain: METRICS

  Datasets:
    - Domain: METRICS
      DatasetType: TARGET_TIME_SERIES
      DataFrequency: 15min
      TimestampFormat: yyyy-MM-dd HH:mm:ss
      Schema:
        Attributes:
          - AttributeName: timestamp
            AttributeType: timestamp
          - AttributeName: metric_name
            AttributeType: string
          - AttributeName: metric_value
            AttributeType: float

  AutoPredictor:
    PredictorName: predictor_v1
    MaxAge: 100
    ForecastHorizon: 3
    ForecastFrequency: 15min

  Forecast:
    ForecastTypes:
      - "0.10"
      - "0.50"
      - "0.90"

No additional advanced settings added when creating the stack. 

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v1.4.0]

**Comment by tabdunabi** [comment]
Hi @nivedha75, thank you for creating this issue. 
Could you please share your `modified version of the csv file` to try reproduce the issue. 
Thanks

**Comment by ihmaws** [comment]
Closing stale issue. Please re-open if issue still exists.
