### ISSUE TITLE
Data Import Lambda function

### ISSUE THREAD

**Issue by hadi-android** [aws-solutions/improving-forecast-accuracy-with-machine-learning#6]
In the import data step, the documentation  states that "To determine if your data must be imported, the solution checks whether data is present, and if its specification has changed, or if the .csv being imported has a different number of rows". I am assuming this refers to createdatasetimportjob/handler.py. But I don’t see which part of the code does these checks like the number of rows and specification? 

In the code, I only see a check for whether the dataset exists as follows:

`    if dataset_import.status == Status.DOES_NOT_EXIST:
        dataset_import.create()`

Thanks in advance

**Comment by pwrmiller** [comment]
Hi - thanks for leaving this question here! 

If you take a look at the source code for the solution, the `dataset_import` you've referenced is an instance of the `DatasetImportJob` class ([reference](https://github.com/awslabs/improving-forecast-accuracy-with-machine-learning/blob/b30da1fe022862c68f1c11bffbf27915f824a308/source/shared/Dataset/dataset_import_job.py#L26_)). To get its status, the handler calls the `status` method of the `DatasetImportJob`. 

Looking at the implementation, `Status.DOES_NOT_EXIST` is returned for a number of reasons:

1. there are no previous imports for the dataset (no data is yet present)
2. if the data is outdated, which is currently determined by inspecting a tag on the dataset against a calculated checksum of the dataset .csv file in S3 

Previous versions of the solution used Amazon S3 Select to determine characteristics of the .csv file being imported, but these proved to be inaccurate checks for user data; depending on if headers and blank lines were available, the solution might incorrectly re-import data, and I believe the documentation has not been updated to reflect this change. Further, if the data changed in-place (e.g. same number of rows, but different data) these checks would not correctly identify a change in data and trigger a re-import. 

The checks for the dataset specification are still present in `dataset.py`, if the specification of the dataset has changed, the solution will not attempt to continue. 

Thanks for providing feedback on the solution - the documentation will be corrected.
