### ISSUE TITLE
build-and-test dependencies install issues

### ISSUE THREAD

**Issue by athewsey** [aws-solutions/improving-forecast-accuracy-with-machine-learning#8]
Trying to build the CDK from source today I encountered a couple of (small) issues:

(1) - In the [source/infrastructure/README](https://github.com/aws-solutions/improving-forecast-accuracy-with-machine-learning/blob/main/source/infrastructure/README.md) we seem to be inconsistent about what folder the commands are run from? first `cd`ing to `source/infrastructure` but then running `pip install -r source/requirements-build-and-test.txt`.

I found that in order for pip to resolve the editable dependencies like `-e cdk_solution_helper_py/helpers_cdk`, I had to be inside the source folder and run `pip install -r requirements-build-and-test.txt`.

(2) - For some reason I don't quite understand, pip errored out due to conflict between `black@2.21.0` requiring `click>=8.0.0`... Even though in the requirements-build-and-test.txt, the version for `black` is left unspecified. Not sure what's going on here with the dependency resolution as I'd have expected it to just pick a version of black that satisfies the other constraints... But for now I worked around it by explicitly requesting `black==21.12b0`.

**Comment by pwrmiller** [comment]
Hello @athewsey - 

Thanks for your feedback. I've confirmed the issues and will ensure that these are fixed for the next maintenance release of the solution. For now, your workaround in (2) is appropriate, and you are correct about (1) - the documentation will be fixed.
